### ISSUE TITLE
Dashboard example does not work as Python script due to --nopass inconsistency

### ISSUE THREAD

**Issue by bcbrock** [ranaroussi/qtpylib#107]
Hi Ran,

I'm trying to run examples/dashboard.py as-is and it crashes:

```
bcbrock@ubuntu-xenial$ python dashboard.py 
Traceback (most recent call last):
  File "dashboard.py", line 35, in <module>
    dashboard.run()
  File "/home/bcbrock/miniconda3/lib/python3.6/site-packages/qtpylib/reports.py", line 358, in run
    if not self.args['nopass'] and self._password != "":
KeyError: 'nopass'
```

I believe it will currently only work if called with the explicit --nopass argument:

```
bcbrock@ubuntu-xenial$ python dashboard.py --nopass
 * Serving Flask app "qtpylib.reports" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 875-155-193
```

Thanks,

Bishop Brock

**Comment by lionelyoung** [comment]
Hi @bcbrock,

PR #101 fixes this

**Comment by bcbrock** [comment]
Thanks!
