### ISSUE TITLE
[strategy example]AttributeError: 'NoneType' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by distagon** [ranaroussi/qtpylib#12]
$ python strategy.py --log strategy/ --ibport 7491 --output strategy/
Active month for ES is: 201612
Server Version: 76
TWS Time at connection:20161024 23:22:22 CST
ESZ2016_FUT not in position. Sending a bracket  SELL order...
Traceback (most recent call last):
  File "strategy.py", line 106, in <module>
    strategy.run()
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/qtpylib/algo.py", line 206, in run
    bar_handler   = self._bar_handler
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/qtpylib/blotter.py", line 909, in listen
    tick_handler(df)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/qtpylib/algo.py", line 491, in _tick_handler
    self.on_tick(self.get_instrument(tick))
  File "strategy.py", line 83, in on_tick
    self.record(take_action=1)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/qtpylib/algo.py", line 439, in record
    self.datastore.record(self.record_ts, *args, **kwargs)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/qtpylib/tools.py", line 478, in record
    row = pd.DataFrame(data=data, index=[timestamp])
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/pandas/core/frame.py", line 266, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/pandas/core/frame.py", line 402, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/pandas/core/frame.py", line 5384, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/pandas/core/frame.py", line 5695, in _homogenize
    raise_cast_failure=False)
  File "/Users/qtpylib_user/anaconda3/envs/qtpylib/lib/python3.5/site-packages/pandas/core/series.py", line 2919, in _sanitize_array
    if subarr.ndim == 0:
AttributeError: 'NoneType' object has no attribute 'ndim'
2016-10-24 23:22:31,191 [INFO]: Algo stopped...
2016-10-24 23:22:31,195 [INFO]: Disconnecting...
2016-10-24 23:22:31,198 [INFO]: Disconnecting from MySQL...

**Comment by homeyi** [comment]
always have some wrong by anaconda.

**Comment by ranaroussi** [comment]
Fixed in version 1.4.95a. Please upgrade.
