### ISSUE TITLE
Futures contract data not being downloaded by blotter.

### ISSUE THREAD

**Issue by rterbush** [ranaroussi/qtpylib#39]
I start by adding the following line to symbols.csv

```
ES,FUT,GLOBEX,USD,201612,0.0,
```

After starting blotter, the line is changed to add a `.0` to the end of the expiry value.

```
ES,FUT,GLOBEX,USD,201612.0,0.0,
```

No ES data is saved to the database.

**Comment by ranaroussi** [comment]
Just uploaded version version `1.5.42`. Please upgrade and let me know if resolved.

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

**Comment by rterbush** [comment]
Blotter now fails to start with the following error:
```
2016-12-06 14:55:20,643 [INFO] qtpylib.blotter: Connecting to Interactive Brokers...
Server Version: 76
TWS Time at connection:20161206 07:55:20 MST
2016-12-06 14:55:21,678 [INFO] qtpylib.blotter: Connection established...
2016-12-06 14:55:21,722 [WARNING] qtpylib.blotter: [IB #321] Error validating request:-'aV' : cause - Invalid account code '0'.
Traceback (most recent call last):
  File "./utils/blotter.py", line 12, in <module>
    blotter.run()
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/qtpylib/blotter.py", line 795, in run
    df['expiry'] = df['expiry'].astype(int)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 3189, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 3056, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 461, in astype
    values=values, **kwargs)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/core/internals.py", line 504, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/home/inmate/workspace/venv/lib/python3.4/site-packages/pandas/types/cast.py", line 531, in _astype_nansafe
    raise ValueError('Cannot convert NA to integer')
ValueError: Cannot convert NA to integer
```

I've tried both after removing the ES instrument from symbols.csv as well as with the minor change to expiry. Both attempts fail.

**Comment by ranaroussi** [comment]
Last version introduced a new bug. Fixed with latest commit (bd750855dd36c66f0e1b6bfb47afbe24828e2079). 

Please upgrade and retry:

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

**Comment by ranaroussi** [comment]
Closing this issue for now. Please reopen if not resolved.

**Comment by rterbush** [comment]
Confirming this is fixed.
