### ISSUE TITLE
File Not Found Error during qtpylib install

### ISSUE THREAD

**Issue by aberja** [ranaroussi/qtpylib#56]
Hi Ran 

I'm wondering if you can help me.  I'm running Anaconda 3.6 and when I try to install qtpylib with "pip install qtpylib --upgrade --no-cache-dir" I receive the following error:

```
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\
Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg'

However, I noticed that qtpylib uninstalled this version:

  Found existing installation: setuptools 27.2.0
    Uninstalling setuptools-27.2.0:
      Successfully uninstalled setuptools-27.2.0

  And installed version 34.3.1:
	
 Successfully installed Jinja2-2.9.5 PyJWT-1.4.2 appdirs-1.4.2 cryptography-1.7.2
 httplib2-0.10.3 idna-2.4 nexmo-1.4.0 packaging-16.8 pyasn1-0.2.3 pymysql-0.7.10
 pyparsing-2.1.10 pysocks-1.6.6 qtpylib-1.5.59 requests-2.13.0 setuptools-34.3.1
 twilio-5.7.0
 
Here is the Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\pip-script.py", line 5, in <module>
    sys.exit(pip.main())
  File "C:\Anaconda3\lib\site-packages\pip\__init__.py", line 249, in main
    return command.main(cmd_args)
  File "C:\Anaconda3\lib\site-packages\pip\basecommand.py", line 252, in main
    pip_version_check(session)
  File "C:\Anaconda3\lib\site-packages\pip\utils\outdated.py", line 102, in pip_
version_check
    installed_version = get_installed_version("pip")
  File "C:\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 838, in get_
installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 644, in __init__
    self.add_entry(entry)
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Anaconda3\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", l
ine 1643, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\
Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg'
```

**Comment by ranaroussi** [comment]
mm... I've never encountered this before.

Try updating `setuptools` using `conda` first:

```bash
$ conda update setuptools
```

...and then try re-installing QTPyLib:

```bash
$ pip install qtpylib --upgrade --no-cache-dir
```

LMK if this works.
Ran

**Comment by aberja** [comment]
Your suggestion worked. However, '$ conda update setuptools' did not update setuptools as it showed that version 27.2.0 was the most current version.  And '$ pip install qtpylib --upgrade --no-cache-dir' didn't install anything as it showed everything was up-to-date.  So I'm not sure why qtpylib originally uninstalled 27.2.0 and stated it installed setuptools 34.3.1.

**Comment by ranaroussi** [comment]
This part of the magic of computers 😁 

I take it that everything works now?

**Comment by aberja** [comment]
Still putting everything together and working thru your Jupyter Notebook, but so far so good.  Thanks.

**Comment by ranaroussi** [comment]
Great news! Closing the issue for now. Please re-open it in case the problem persist.
