### ISSUE TITLE
Error getting data from IB in workflow

### ISSUE THREAD

**Issue by ghost** [ranaroussi/qtpylib#60]
external_data = wf.get_data_ib("AAPL",start="2012-01-01", resolution="1 day")

returns this.
```bash
-------------------------

Traceback (most recent call last):
  File "/Users/damani/PycharmProjects/blackbox/strategy.py", line 72, in <module>
    external_data = wf.get_data_ib("AAPL",start="2012-01-01", resolution="1 day")
  File "/Users/damani/anaconda/lib/python3.6/site-packages/qtpylib/workflow.py", line 265, in get_data_ib
    return prepare_data(instrument, data, output_path=output_path)
  File "/Users/damani/anaconda/lib/python3.6/site-packages/qtpylib/workflow.py", line 372, in prepare_data
    df.index = df.index.tz_localize(tools.get_timezone()).tz_convert("UTC")
  File "/Users/damani/anaconda/lib/python3.6/site-packages/pandas/util/decorators.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/damani/anaconda/lib/python3.6/site-packages/pandas/tseries/index.py", line 1821, in tz_localize
    tz = tslib.maybe_get_tz(tz)
  File "pandas/tslib.pyx", line 1753, in pandas.tslib.maybe_get_tz (pandas/tslib.c:32549)
  File "pandas/tslib.pyx", line 1768, in pandas.tslib.maybe_get_tz (pandas/tslib.c:32362)
  File "/Users/damani/anaconda/lib/python3.6/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Etc/GMT-17'
```

**Comment by ranaroussi** [comment]
Fixed in version 1.5.76 (Sep 26 2017). Closing this for now
